title: Trenčiansky Útulok
description: >
  Nájdite si svojho nového štvornohého člena do Vašej rodiny.
  Pomôžte nájsť zatúlaného psíka a pomôcť mu vrátiť sa späť do svojho domova.
  OZ Trenčiansky Útulok prevádzkuje Karanténnu stanicu v Trenčíne.
  Postupne sa z Karanténnej stanice Trenčín stáva útulok pre psíkov v Trenčíne.

url: http://localhost:4000
baseurl: ""

google_analytics: ""
fb_album_link: https://embedsocial.com/facebook_album/pro/391cc6bc1c01f1a6b732c89d6cd5d8af80257c5f

email: utulok.trencin@gmail.com
phone: +421-915-785-007​
fb_username: TrencianskyUTULOK

# site
timezone: Europe/Bratislava
excerpt_separator: <!--more-->
permalink: pretty

# build
markdown: kramdown
sass:
  style: ""
  sass_dir: _sass

exclude:
  - vendor/
  - bower.json
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# override defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
